export const FETCH_PREVIOUS_ORDERS = "CONTRACTOR/ORDER/PREVIOUS/FETCH";
export const REQUEST_PREVIOUS_ORDERS='CONTRACTOR/ORDER/PREVIOUS/REQUEST';
export const REQUEST_PREVIOUS_ORDERS_SUCCESS='CONTRACTOR/ORDER/PREVIOUS/SUCCESS';
export const REQUEST_PREVIOUS_ORDERS_FAILED='CONTRACTOR/ORDER/PREVIOUS/FAILED';
export const STOP_FETCH_PREVIOUS_ORDERS = "CONTRACTOR/ORDER/PREVIOUS/STOP";
export const REMOVE_PREVIOUS_ORDER="CONTRACTOR/ORDER/PREVIOUS/REMOVE";
export const REMOVE_ORDER="CONTRACTOR/ORDER/PREVIOUS/REMOVE_ORDER";