export const FETCH_ACCEPTED_ORDERS = "CONTRACTOR/ACCEPTED_ORDER/FETCH";
export const REQUEST_ACCEPTED_ORDERS='CONTRACTOR/ACCEPTED_ORDER/REQUEST';
export const REQUEST_ACCEPTED_ORDERS_SUCCESS='CONTRACTOR/ACCEPTED_ORDER/SUCCESS';
export const REQUEST_ACCEPTED_ORDERS_FAILED='CONTRACTOR/ACCEPTED_ORDER/FAILED';
