export let FETCH_ORDERS = "CONTRACTOR/ORDER/FETCH";
export const REQUEST_ORDERS='CONTRACTOR/ORDER/REQUEST';
export const REQUEST_ORDERS_SUCCESS='CONTRACTOR/ORDER/SUCCESS';
export const REQUEST_ORDERS_FAILED='CONTRACTOR/ORDER/FAILED';

export let GET_DAY_OF_POUR_ORDERS = "CONTRACTOR/ORDER/DAYOFPOUR/GET";
export let GET_ACCEPTED_ORDERS = "CONTRACTOR/ORDER/ACCEPTED/GET";
export const GET_PENDING_ORDERS='CONTRACTOR/ORDER/PENDING/GET';

export const MERGE_ORDERS='CONTRACTOR/ORDER/PENDING/MERGE_ORDERS';

export const ADD_ORDER='CONTRACTOR/ORDER/PENDING/ADD_ORDER';
export const REMOVE_ORDER='CONTRACTOR/ORDER/PENDING/REMOVE_ORDER';
