export const GET_BIDDING_ORDERS ='CONTRACTOR/ORDER/BIDDING';
export const PENDING_ORDERS ='CONTRACTOR/ORDERS/PENDING';
export const ACCEPTED_ORDERS ='CONTRACTOR/ORDERS/ACCEPTED';
export const REMOVE_BID='CONTRACTOR/ORDER/REMOVE_BID';
export const SINGLE_ORDER='ORDER/SINGLE_ORDER';
export const ADD_ORDER='ORDER/ADD_ORDER';
