export const BIDDING_ORDERS ='CONTRACTOR/ORDER/BIDDING';
export const PENDING_ORDERS ='CONTRACTOR/ORDERS/PENDING';
export const ACCEPTED_ORDERS ='CONTRACTOR/ORDERS/ACCEPTED';
export const REMOVE_BID='CONTRACTOR/ORDER/REMOVE_BID';
export const SINGLE_ORDER='ORDER/SINGLE_ORDER';
export const GET_SINGLE_ACCEPTED_ORDER='ORDER/GET_SINGLE_ACCEPTED_ORDER';
export const ADD_ORDER='ORDER/ADD_ORDER';

export const CANCEL_ORDER='ORDER/CANCEL_ORDER';