
export const FETCH_PENDING_ORDERS = "CONTRACTOR/ORDER/FETCH";
export const REQUEST_PENDING_ORDERS='CONTRACTOR/ORDER/REQUEST';
export const REQUEST_PENDING_ORDERS_SUCCESS='CONTRACTOR/ORDER/SUCCESS';
export const REQUEST_PENDING_ORDERS_FAILED='CONTRACTOR/ORDER/FAILED';
export const REQUEST_ARCHIVE_ORDER='CONTRACTOR/ORDER/ARCHIVE/REQUEST';
export const REQUEST_ARCHIVE_ORDER_SUCCESS='CONTRACTOR/ORDER/ARCHIVE/REQUEST/SUCCESS';
export const REQUEST_ARCHIVE_ORDER_FAILED='CONTRACTOR/ORDER/ARCHIVE/REQUEST/FAILED';

export const REQUEST_REMOVE_BID='CONTRACTOR/ORDER/PENDING/REMOVE/REQUEST';
export const REQUEST_REMOVE_BID_SUCCESS='CONTRACTR/ORDER/PENDING/REMOVE/SUCCESS';
export const REQUEST_REMOVE_BID_FAILED='CONTRACTR/ORDER/PENDING/REMOVE/FAILED';

export const REQUEST_ACCEPT_BID = "CONTRACTOR/ORDER/PENDING/ACCEPT/BID";

export const STOP_FETCH_PENDING_ORDERS="CONTRACTOR/ORDER/PENDING/STOP";