export const FETCH_PENDING_ORDERS = "CONTRACTOR/ORDER/FETCH";
export const REQUEST_PENDING_ORDERS='CONTRACTOR/ORDER/REQUEST';
export const REQUEST_PENDING_ORDERS_SUCCESS='CONTRACTOR/ORDER/SUCCESS';
export const REQUEST_PENDING_ORDERS_FAILED='CONTRACTOR/ORDER/FAILED';
export const REQUEST_ARCHIVE_ORDER='CONTRACTOR/ORDER/ARCHIVE';
